{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-1112",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://access.redhat.com/articles/3422521"
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:1268"
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:1269"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1112"
        },
        {
          "url": "https://review.gluster.org/#/c/19899/1..2"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "glusterfs server before versions 3.10.12, 4.0.2 is vulnerable when using 'auth.allow' option which allows any unauthenticated gluster client to connect from any network to mount gluster storage volumes. NOTE: this vulnerability exists because of a CVE-2018-1088 regression."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-04-25T12:29Z",
  "lastModifiedDate": "2018-05-02T01:29Z"
}