{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2019-15486",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://github.com/ierror/django-js-reverse/compare/v0.9.0...v0.9.1",
          "name": "https://github.com/ierror/django-js-reverse/compare/v0.9.0...v0.9.1",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/ierror/django-js-reverse/pull/81",
          "name": "https://github.com/ierror/django-js-reverse/pull/81",
          "refsource": "MISC",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "django-js-reverse (aka Django JS Reverse) before 0.9.1 has XSS via js_reverse_inline."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2019-08-23T13:15Z",
  "lastModifiedDate": "2019-08-23T14:11Z"
}